"""
Simple PDF report generator — plain text only, no complex layout.
"""
from __future__ import annotations
from datetime import datetime
from fpdf import FPDF


def _clean(text: str) -> str:
    """Strip markdown and replace anything outside Latin-1."""
    text = (text.replace("**", "").replace("##", "").replace("#", "")
                .replace("---", "").replace("–", "-").replace("—", "-")
                .replace("‘", "'").replace("’", "'")
                .replace("“", '"').replace("”", '"')
                .replace("•", "*").replace("…", "...")
                .replace(" ", " "))
    return text.encode("latin-1", errors="replace").decode("latin-1")


def build_pdf(
    sector: str,
    growth: float,
    risk: float,
    lending: float,
    report_text: str,
    top_features: dict | None = None,
    company_name: str = "SME",
) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 15, 15)
    W = 180  # effective content width

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(W, 10, "Lloyds SME Intelligence Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(W, 7, f"Group 33  |  {datetime.now().strftime('%d %B %Y  %H:%M')}", ln=True, align="C")
    pdf.ln(5)

    # Divider
    pdf.set_draw_color(0, 106, 77)
    pdf.set_line_width(0.8)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(5)

    # Overview
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(W, 8, "Company Overview", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(W, 6, f"Sector: {_clean(sector)}", ln=True)
    pdf.cell(W, 6, f"Company: {_clean(company_name)}", ln=True)
    pdf.ln(4)

    # Scores
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(W, 8, "Prediction Scores", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for label, prob in [("Growth Opportunity", growth), ("Risk Signal", risk), ("Lending Need", lending)]:
        if prob >= 0.7:   status = "HIGH"
        elif prob >= 0.4: status = "MEDIUM"
        else:             status = "LOW"
        pdf.cell(W, 6, f"  {label}: {prob:.1%}  ({status})", ln=True)
    pdf.ln(4)

    # SHAP features
    if top_features:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(W, 8, "Key Feature Drivers (SHAP)", ln=True)
        for lbl in ["growth", "risk", "lending"]:
            feats = top_features.get(lbl, [])
            if not feats:
                continue
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(W, 6, f"  {lbl.capitalize()}:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for i, (fname, fval) in enumerate(feats[:5]):
                sign = "+" if fval >= 0 else ""
                pdf.cell(W, 6, f"    {i+1}. {_clean(fname)}: {sign}{fval:.4f}", ln=True)
        pdf.ln(4)

    # AI report
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(W, 8, "AI Analysis", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for line in _clean(report_text).split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(3)
        else:
            pdf.multi_cell(W, 6, line)
    pdf.ln(4)

    # Disclaimer
    pdf.set_draw_color(0, 106, 77)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(W, 5,
        "This report is generated by ML models and a generative AI system. "
        "For internal use only. Data from UK Companies House public bulk download. "
        "Lloyds Banking Group - Group 33 Dissertation Project.")

    return bytes(pdf.output())


def pdf_download_button(
    report_text: str,
    sector: str,
    growth: float,
    risk: float,
    lending: float,
    top_features: dict | None = None,
    company_name: str = "SME",
    key: str = "pdf_download",
):
    import streamlit as st
    try:
        pdf_bytes = build_pdf(
            sector=sector, growth=growth, risk=risk, lending=lending,
            report_text=report_text, top_features=top_features,
            company_name=company_name,
        )
        fname = (f"lloyds_sme_{sector.replace(' ', '_').lower()}"
                 f"_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf")
        st.download_button(
            label="📥 Download Report as PDF",
            data=pdf_bytes,
            file_name=fname,
            mime="application/pdf",
            key=key,
        )
    except Exception as e:
        st.error(f"PDF error: {e}")
